// <auto-generated />
namespace Bugtracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class update_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201706222103192_update_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
